export enum LearningTaskType {
  MEANING_CHOICE = "MEANING_CHOICE",
  ACTIVE_RECALL_TYPING = "ACTIVE_RECALL_TYPING",
  SPELLING_RECALL_TYPING = "SPELLING_RECALL_TYPING",
  RELATION_CHOICE = "RELATION_CHOICE",
  CONFUSABLE_CHOICE = "CONFUSABLE_CHOICE",
}

export const TASK_PROTOCOL_VERSION = "v1";
export const TASK_GENERATOR_VERSION = "v1";
