/**
 * Scene Content Contract Candidate V0 error codes.
 * Experimental / Not a Standard.
 */

export const SceneContentErrorCode = {
  CONTENT_PACK_ID_INVALID: "CONTENT_PACK_ID_INVALID",
  CONTENT_SCHEMA_VERSION_INVALID: "CONTENT_SCHEMA_VERSION_INVALID",
  CONTENT_CLUSTER_NOT_FOUND: "CONTENT_CLUSTER_NOT_FOUND",
  CONTENT_SKELETON_NOT_FOUND: "CONTENT_SKELETON_NOT_FOUND",
  CONTENT_PROVENANCE_INVALID: "CONTENT_PROVENANCE_INVALID",
  CONTENT_TARGET_INVALID: "CONTENT_TARGET_INVALID",
  CONTENT_TARGET_DUPLICATE: "CONTENT_TARGET_DUPLICATE",
  CONTENT_SCENE_ORDER_DUPLICATE: "CONTENT_SCENE_ORDER_DUPLICATE",
  CONTENT_CANONICAL_KEY_INVALID: "CONTENT_CANONICAL_KEY_INVALID",
  CONTENT_BUNDLED_IDENTITY_MISMATCH: "CONTENT_BUNDLED_IDENTITY_MISMATCH",
  CONTENT_DISPLAY_FORM_MISSING: "CONTENT_DISPLAY_FORM_MISSING",
  CONTENT_MEANING_GLOSS_MISSING: "CONTENT_MEANING_GLOSS_MISSING",
  CONTENT_FRAME_NOT_FOUND: "CONTENT_FRAME_NOT_FOUND",
  CONTENT_FRAME_ID_DUPLICATE: "CONTENT_FRAME_ID_DUPLICATE",
  CONTENT_FRAME_BINDING_MISSING: "CONTENT_FRAME_BINDING_MISSING",
  CONTENT_ENTITY_NOT_IN_FRAME: "CONTENT_ENTITY_NOT_IN_FRAME",
  CONTENT_ENTITY_SENSE_BINDING_MISMATCH: "CONTENT_ENTITY_SENSE_BINDING_MISMATCH",
  CONTENT_ENTITY_BINDING_DUPLICATE: "CONTENT_ENTITY_BINDING_DUPLICATE",
  CONTENT_ROLE_NOT_FOUND: "CONTENT_ROLE_NOT_FOUND",
  CONTENT_FACT_NOT_FOUND: "CONTENT_FACT_NOT_FOUND",
  CONTENT_FACT_NOT_BOUND_TO_FRAME: "CONTENT_FACT_NOT_BOUND_TO_FRAME",
  CONTENT_CONNECT_FACT_NOT_IN_FRAME: "CONTENT_CONNECT_FACT_NOT_IN_FRAME",
  CONTENT_FACT_ARGUMENT_MISMATCH: "CONTENT_FACT_ARGUMENT_MISMATCH",
  CONTENT_FACT_DIRECTION_MISMATCH: "CONTENT_FACT_DIRECTION_MISMATCH",
  CONTENT_FACT_ENTITY_ABSENT: "CONTENT_FACT_ENTITY_ABSENT",
  CONTENT_UNKNOWN_FIELD: "CONTENT_UNKNOWN_FIELD",
  CONTENT_CONTRAST_TARGET_NOT_FOUND: "CONTENT_CONTRAST_TARGET_NOT_FOUND",
  CONTENT_CONTRAST_SELF: "CONTENT_CONTRAST_SELF",
  CONTENT_CONTRAST_KIND_INVALID: "CONTENT_CONTRAST_KIND_INVALID",
  CONTENT_CONTRAST_COPY_EMPTY: "CONTENT_CONTRAST_COPY_EMPTY",
  CONTENT_RECALL_LEAKS_FORM: "CONTENT_RECALL_LEAKS_FORM",
  CONTENT_PROBE_SKILLS_INVALID: "CONTENT_PROBE_SKILLS_INVALID",
  CONTENT_BUILD_PROFILE_INCOMPLETE: "CONTENT_BUILD_PROFILE_INCOMPLETE",
  CONTENT_STRENGTHEN_PROFILE_INCOMPLETE: "CONTENT_STRENGTHEN_PROFILE_INCOMPLETE",
  CONTENT_OUTCOME_FORBIDDEN: "CONTENT_OUTCOME_FORBIDDEN",
  CONTENT_REGISTRY_UNAPPROVED: "CONTENT_REGISTRY_UNAPPROVED",
  CONTENT_REGISTRY_DUPLICATE: "CONTENT_REGISTRY_DUPLICATE",
  CONTENT_PACK_UNRESOLVED: "CONTENT_PACK_UNRESOLVED",
} as const;

export type SceneContentErrorCode =
  (typeof SceneContentErrorCode)[keyof typeof SceneContentErrorCode];

export interface SceneContentIssue {
  code: SceneContentErrorCode;
  path: string;
}

export type SceneContentValidation =
  | { ok: true }
  | { ok: false; issues: SceneContentIssue[] };
