export const REAL_RELEASE_SERVER_ENV = {
  CONTEXTUAL_CONTENT_REVIEW_ENABLED: "0",
  CONTEXTUAL_CONTENT_REVIEW_WRITE_ENABLED: "0",
  CONTEXTUAL_CONTENT_PROMOTION_ENABLED: "0",
  CONTEXTUAL_CONTENT_PROMOTION_WRITE_ENABLED: "0",
  CONTEXTUAL_CONTENT_RELEASE_ENABLED: "1",
  CONTEXTUAL_CONTENT_RELEASE_WRITE_ENABLED: "0",
  CONTEXTUAL_RELEASE_RUNTIME: "file",
} as const;
