export enum VocabularySkill {
  MEANING_RECOGNITION = "MEANING_RECOGNITION",
  LISTENING_RECOGNITION = "LISTENING_RECOGNITION",
  SEMANTIC_CONNECTION = "SEMANTIC_CONNECTION",
  ACTIVE_RECALL = "ACTIVE_RECALL",
  SPELLING_RECALL = "SPELLING_RECALL",
  CONTEXT_USE = "CONTEXT_USE",
}

export const VOCABULARY_SKILLS: readonly VocabularySkill[] = [
  VocabularySkill.MEANING_RECOGNITION,
  VocabularySkill.LISTENING_RECOGNITION,
  VocabularySkill.SEMANTIC_CONNECTION,
  VocabularySkill.ACTIVE_RECALL,
  VocabularySkill.SPELLING_RECALL,
  VocabularySkill.CONTEXT_USE,
] as const;
