import { AnswerMode, EvidenceOutcome } from "../evidence.types";
import { MasteryStage } from "../mastery-stage";
import { VocabularySkill } from "../vocabulary-skill";
import type { LearningPolicy } from "./learning-policy";

export const DEFAULT_LEARNING_POLICY: LearningPolicy = {
  version: "v1",
  skillUpdate: {
    ewmaAlpha: 0.25,
    skippedEwmaAlpha: 0.08,
    recentPerformanceLimit: 10,
    outcomeTargetScores: {
      [EvidenceOutcome.INDEPENDENT_CORRECT]: 1.0,
      [EvidenceOutcome.CORRECT]: 0.85,
      [EvidenceOutcome.ASSISTED_CORRECT]: 0.55,
      [EvidenceOutcome.INCORRECT]: 0.0,
      [EvidenceOutcome.TIMEOUT]: 0.0,
      [EvidenceOutcome.SKIPPED]: 0.5,
    },
    answerModeWeights: {
      [AnswerMode.MULTIPLE_CHOICE]: 0.7,
      [AnswerMode.MATCHING]: 0.7,
      [AnswerMode.DRAG_DROP]: 0.75,
      [AnswerMode.TAP_TARGET]: 0.75,
      [AnswerMode.TYPING]: 1.0,
      [AnswerMode.SPELLING]: 1.0,
    },
    answerModeNeutralFloor: 0.6,
    difficultyInfluence: 0.1,
  },
  confidence: {
    skillAttemptDenom: 8,
    skillIndependentDenom: 5,
    skillSessionDenom: 4,
    skillDayDenom: 4,
    skillWeights: {
      attempts: 0.25,
      independent: 0.3,
      sessions: 0.25,
      days: 0.2,
    },
    masteryEvidenceDenom: 10,
    masterySessionDenom: 5,
    masteryDayDenom: 5,
    masteryTaskTypeDenom: 4,
    masteryIndependentDenom: 6,
    masteryWeights: {
      evidence: 0.15,
      sessions: 0.25,
      days: 0.25,
      taskTypes: 0.2,
      independent: 0.15,
    },
  },
  recognition: {
    minIndependentSuccesses: 2,
    minDistinctSessions: 2,
    skills: [
      VocabularySkill.MEANING_RECOGNITION,
      VocabularySkill.LISTENING_RECOGNITION,
    ],
  },
  connection: {
    meaningRecognitionMinScore: 0.7,
    semanticConnectionMinScore: 0.55,
    minDistinctSessions: 2,
  },
  recall: {
    minScore: 0.65,
    minIndependentSuccesses: 2,
    minDistinctSessions: 2,
    productionSkills: [
      VocabularySkill.ACTIVE_RECALL,
      VocabularySkill.SPELLING_RECALL,
    ],
    productionAnswerModes: [AnswerMode.TYPING, AnswerMode.SPELLING],
  },
  usage: {
    contextUseMinScore: 0.65,
    minDistinctContextVariants: 2,
    minIndependentSuccesses: 1,
  },
  mastery: {
    meaningRecognitionMinScore: 0.8,
    productionMinScore: 0.75,
    contextUseMinScore: 0.7,
    minDistinctPracticeDays: 3,
    minDistinctTaskTypes: 3,
    minIndependentSuccesses: 5,
    minDaysSinceFirstSeen: 7,
    maxUnresolvedWeaknessSeverity: 0.6,
    skillWeights: {
      [VocabularySkill.MEANING_RECOGNITION]: 0.2,
      [VocabularySkill.LISTENING_RECOGNITION]: 0.1,
      [VocabularySkill.SEMANTIC_CONNECTION]: 0.15,
      [VocabularySkill.ACTIVE_RECALL]: 0.25,
      [VocabularySkill.SPELLING_RECALL]: 0.15,
      [VocabularySkill.CONTEXT_USE]: 0.15,
    },
    demotionRecentWindow: 6,
    demotionMinFailures: 3,
    demotionMinFailureSessions: 2,
  },
  weakness: {
    repeatedErrorWindow: 3,
    repeatedErrorMinFailures: 2,
    hintDependencyWindow: 5,
    hintDependencyMinAssisted: 3,
    confusionMinCount: 2,
    spellingErrorWindow: 3,
    spellingErrorMinCount: 2,
    slowResponseRelativeMultiplier: 1.8,
    slowResponseFallbackMs: 8000,
    slowResponseMinBaselineSamples: 4,
    instabilityWindow: 6,
    instabilityMinAlternations: 4,
    recoveryIndependentSuccesses: 2,
    recoverySeverityDecay: 0.25,
    resolveSeverityThreshold: 0.15,
    triggerSeverityStep: 0.2,
    initialSeverity: 0.45,
  },
  retention: {
    minIndependentSuccessesForStable: 2,
    fadingOnFailureMinStage: MasteryStage.USABLE,
    fadingScoreDrop: 0.2,
    recoveringRequiresDifferentSession: true,
  },
  review: {
    intervalDaysByStage: {
      [MasteryStage.UNSEEN]: 1,
      [MasteryStage.EXPOSED]: 1,
      [MasteryStage.RECOGNIZED]: 2,
      [MasteryStage.CONNECTED]: 3,
      [MasteryStage.RECALLED]: 4,
      [MasteryStage.USABLE]: 7,
      [MasteryStage.MASTERED]: 14,
    },
    fadingMultiplier: 0.35,
    recoveringMultiplier: 0.5,
  },
};
